version: "3.9"

services:
  db:
    image: docker.io/postgres:15
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:  # healthcheck para o PostgreSQL
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_healthy

  localstack:
    image: docker.io/localstack/localstack:3
    environment:
      - SERVICES=s3,iam,ec2,sns,sqs
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/tmp/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  pgdata:
  localstack_data: